name: CI

on:
  workflow_dispatch:
  workflow_call:
  
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019 

    env:
      Solution_Name: xlDuckDb.sln   
      Test_Project_Path: UnitTests\UnitTests.csproj   

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

   # Setup vstest
    - name: set up VSTest
      uses: darenm/Setup-VSTest@v1

    # Restore nuget packages
    - name: Execute unit tests
      run: nuget restore $env:Solution_Name

    # Build
    - name: Build solution
      run: msbuild $env:Solution_Name -t:rebuild -property:Configuration=Release -property:ExcelDnaCreate32BitAddIn=false -property:ExcelDna64BitAddInSuffix= -property:RunExcelDnaPack=false -property:ExcelDna32BitAddInSuffix=32

    # Run tests
    - name: vs test solution
      #uses: tonyhallett/vstest-solution-action@v1.0.0
      run: vstest.console.exe /Platform:x64 .\UnitTests\bin\x64\Release\UnitTests.dll

    # Upload binary
    - name: "Upload binary"
      uses: actions/upload-artifact@v4
      with:
        name: xlduckdb-${{ github.sha }}
        path: .\xlDuckDb\bin\x64\Release\*.*
        retention-days: 1      

