name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-2019
    permissions:
      contents: write
    steps:
    - uses: ./.github/workflows/ci.yml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "xlduckdb*.*"
        makeLatest: true
        allowUpdates: true
        artifactErrorsFailBuild: true
