name: Releases

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        default: dry-run
        type: string  
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-2019
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/ci.yml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "xlduckdb*.*"
        makeLatest: true
        allowUpdates: true
        artifactErrorsFailBuild: true
