name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: ZIP release artifact
      run: Compress-Archive -Path ./xlDuckDb/bin/Release/net6.0-windows/*.* -Destination xlduckdb.zip

    # Create release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "xlduckdb.zip"
        makelatest: true
        allowupdates: true
        artifacterrorsfailbuild: true